/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface LoginUser$Json$Params {

/**
 * The user name for login
 */
  username?: string;

/**
 * The password for login in clear text
 */
  password?: string;
}

export function loginUser$Json(http: HttpClient, rootUrl: string, params?: LoginUser$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, loginUser$Json.PATH, 'get');
  if (params) {
    rb.query('username', params.username, {});
    rb.query('password', params.password, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

loginUser$Json.PATH = '/user/login';
