/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pet } from '../../models/pet';

export interface UpdatePetWithForm$Json$Params {

/**
 * ID of pet that needs to be updated
 */
  petId: number;

/**
 * Name of pet that needs to be updated
 */
  name?: string;

/**
 * Status of pet that needs to be updated
 */
  status?: string;
}

export function updatePetWithForm$Json(http: HttpClient, rootUrl: string, params: UpdatePetWithForm$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Pet>> {
  const rb = new RequestBuilder(rootUrl, updatePetWithForm$Json.PATH, 'post');
  if (params) {
    rb.path('petId', params.petId, {});
    rb.query('name', params.name, {});
    rb.query('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pet>;
    })
  );
}

updatePetWithForm$Json.PATH = '/pet/{petId}';
